### ISSUE TITLE
Carbon Site fails in IE11 after upgrade from marked@0.7.0 to 0.8.0

### ISSUE THREAD

**Issue by mrw100** [cerner/carbon-site-helpers#32]
**Describe the bug**
A syntax error is thrown when you try to access carbon's dev site, which uses this helper. There is a known error in markedjs@0.8.0 that breaks support of IE.

Workaround specified in the markedjs github issue is to import marked from lib:
https://github.com/markedjs/marked/issues/1585#issuecomment-570830943

**To Reproduce**

1. Launch the carbon dev site in IE
https://engineering.cerner.com/carbon-graphs/#/

**Expected behavior**
The site should render in Internet Explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/1413706/75694879-d6e96780-5c6e-11ea-99dc-8f0e0e4f620b.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser Internet Explorer 11

**Comment by ShettyAkarsh** [comment]
PR #33 Fixed this. hence closing this now.

**Comment by pranav300** [comment]
Reopening the issue as this wasn't fixed by the PR #33.
If we change import to require, Something like this: 
`const marked = require('marked/lib/marked');`
It seemed to work.
